### ISSUE TITLE
5.1版本更新后无法获取OA服务器

### ISSUE THREAD

**Issue by Hellobaka** [Haocen2004/bh3_login_simulation#9]
### 描述
昨天，也就是5.0.0版本时，扫码器仍旧可用。今日，也就是5.1.0版本更新之后，可以看到bilibili账号正常登录，但是无法获取OA服务器。
使用手机端可以正常扫码登录，而且在设置中将版本号写到5.1.0重启之后依旧无法解决问题
### 示例
![image](https://user-images.githubusercontent.com/50934714/130003106-a3de3731-4c8b-4e4f-a0e0-2b31e9a5fecd.png)

**Comment by asuszwbUbuntu** [comment]
我也是一样的，5.1版本无法扫码登陆

**Comment by Haocen2004** [comment]
已经修复

**Comment by asuszwbUbuntu** [comment]
好耶！！！！！！！！QAQ





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haocen2004/bh3_login_simulation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月20日(星期五) 上午7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haocen2004/bh3_login_simulation] 5.1版本更新后无法获取OA服务器 (#9)





 
已经修复
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
